# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  - binary: release-manager-bot
    id: release-manager-bot
    main: .
    goarch:
      - amd64
    goos:
      - darwin
      - linux
    env:
      - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile-goreleaser
    image_templates:
      - "quay.io/lunarway/release-manager-bot:{{ .Tag }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  skip: true
