apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: release-manager-bot
  description: Bot
  annotations:
    backstage.io/techdocs-ref: 'github:https://github.com/spotify/backstage.git'
spec:
  type: service
  lifecycle: production
  owner: guest