server:
  address: "127.0.0.1"
  port: 8080
  public_url: "http://localhost:8080"

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 0
app_configuration:
  pull_request_preamble: "I am echo bot."